### ISSUE TITLE
features_count = 0 == unknown ?

### ISSUE THREAD

**Issue by rouault** [bjornharrtell/flatgeobuf#11]
https://github.com/bjornharrtell/flatgeobuf/blob/master/src/fbs/header.fbs mentions
```
  features_count: ulong;        // Number of features in the dataset (0 = unknown)
```
Is 0 == unknown still true ? I guess this might make sense for a writer that would operate in pure streaming mode, in which case none of the packed Hilbert R-tree indext and Feature offsets index sections should be there. (https://github.com/bjornharrtell/flatgeobuf doesn't indicate that the Feature offsets index section can be optional). As far as I can see, the GDAL driver probably doesn't handle 0 == unknown properly

**Comment by bjornharrtell** [comment]
Yeah the intent here is that it should support streaming mode.
