### ISSUE TITLE
Support for circular/arc geometries

### ISSUE THREAD

**Issue by boergo** [bjornharrtell/flatgeobuf#13]

**Comment by bjornharrtell** [comment]
Looked into this a bit and while it would probably be quite simple to add support for the basic CIRCULARSTRING type perhaps it's not of much value without also having COMPOUNDCURVE, CURVEPOLYGON, MULTICURVE and MULTISURFACE and these have the same problems/complexity as GEOMETRYCOLLECTION i.e they are non homogenous collections and can be nested.

**Comment by bjornharrtell** [comment]
That said, I'm doing it anyway in https://github.com/bjornharrtell/flatgeobuf/pull/14. :)
