### ISSUE TITLE
Excessive point serialization overhead?

### ISSUE THREAD

**Issue by jagill** [bjornharrtell/flatgeobuf#19]
Serializing a (2d) point uses 136 bytes (which in the current implementation is held in a 144-byte capacity `byte[]`).  A WKB serialization takes 21 bytes.  A WKB that is padded for alignment would be 24 bytes (endian[1], type[4], padding[3], x[8], y[8]).

Assuming 8 magic bytes and about 13 bytes for the header, could the size be closer to 40 bytes? (magic[8] + header_plus_padding[16] + x[8] + y[8])?

This is relevant if you are parsing a large column of geometries; it would reduce network IO and memory usage by ~66%.

**Comment by bjornharrtell** [comment]
Interesting observation! Assuming this size overhead is coming from the flatbuffers encoding, it's something I've thought about before, and it's actually the reason I made Feature properties a custom encoding. I did not do any digging into what was the actual cause of overhead back then and assumed that encoding key/value collections was simply a bad fit for flatbuffers which was supported by a statement on the flatbuffers site that I can no longer find. For reference, the old feature fbs schema was https://github.com/bjornharrtell/flatgeobuf/blob/7d61b43c57b52b70dc903b1db40433cc067a369e/src/fbs/feature.fbs.

Back on topic. Just to confirm, you are saying that in a flatgeobuf file that contains multiple point features each such feature will require 136 bytes? My immediate guess is that the overhead comes from the flatbuffers tables which each has as vtable. Before 2.0.0 I didn't have a separate Geometry and Feature table so might have been a little bit smaller but the separation was introduced for a good reason. If time permits I'll see if I can analyse this in more detail, it should be possible to explain exactly what each byte is used for.

Flatbuffers have the vtables to allow for backwards compatible versioning and extension of the format. One could reason that an optimally performing format should use a static structure fx the final serialization variant of FBE. This is discussed in https://github.com/bjornharrtell/flatgeobuf/issues/8.

Out of curiosity, you refer to a padded WKB which I'm not familiar with. Is this a known and used concept?

**Comment by bjornharrtell** [comment]
I see now that you are thinking of a use case where each point is encoded in isolation, each with it's own header. Not sure about that usage vs. I/O efficiency.

Made a testcase at https://github.com/bjornharrtell/flatgeobuf/blob/aa2337c4d304e406908ab82644bbc3a3cf6e96c8/src/cpp/test/point.h to verify what sizes the flatbuffer encoding will result in. I'm pretty sure they are expected sizes but will see if I can get some confirmation. I would still say one would need a more static format/encoding like FBE to reduce size.

**Comment by bjornharrtell** [comment]
Discussed with flatbuffers people and there is an expected overhead on small buffers.

**Comment by jagill** [comment]
Sorry for the delay in response.  Thanks for looking into this!  First, the context for these questions is evaluating whether a flatgeobuff would be good for [Presto](https://prestodb.io)'s geospatial capabilities.  Currently much of the cost is in serialization/deserialization, so the idea of a zero-copy deserialization is enticing.  Presto's inter-worker serialization uses a columnar format to exchange chunks of work.  Some of these columns maybe geometries, and the most common geometry is a point.  Since workloads can easily top 10 billion rows, the overhead for a single point is important.

To answer some questions:
1. Padded WKB is not a real thing, I was just using that as an example of what you might hope the minimum size of an aligned serialized point would be.  It would be nice, tho, and might be a fruitful thing to try.
2. As you figured out already, I am primarily considering the case of many points serialized individually.  It's an interesting option to serialize all the geometries in a column in a single buffer (presumably amortizing the overhead), however it would require more surgery than I'm currently scoping for this stage.
3. This serialization is entirely in-flight between same-version workers, so my use case doesn't require versioning.
4. Digging into the serialized form more, I find that the 136 bytes is comprised of:
  A. 8 bytes: magic bytes
  B. 64 bytes: header meta
    i. 8 bytes for feature count
    ii. 1 byte for geometry type
    iii. a size 0 int[] for columns
    iv. Overhead?
  C. 64 bytes: geometry
    i. 2*8 bytes for two double coords
    ii. Overhead?

So it seems like the header and geometry overhead is the dominating factor (I guess this is what the flatbuffers people referred to?).  The actual size of information is about 8 + 8 + 1 + 2*8, or 40 bytes with padding (comparable to "padded WKB").

I don't yet understand what the columns are in the serialization, nor the difference between geometry and feature.

**Comment by bjornharrtell** [comment]
Ok I understand your use case a bit more now and it doesn't seem to be an optimal fit for a general simple feature container like FlatGeobuf. The "Feature" concept is geometry + attributes (columns + properties in the FlatGeobuf schema. What you seem to need is an optimal encoding for geometry only. If you are constrained to points I would simply store them as pairs of doubles and if you need to support other geometry types, a padded WKB variant seems to be a pretty good idea.

**Comment by jagill** [comment]
Sounds about right; thanks!
