### ISSUE TITLE
Logo proposal 

### ISSUE THREAD

**Issue by dee-y** [bjornharrtell/flatgeobuf#2]
Hello, i am a graphic designer. I would love to contribute a logo free for your project if you would have me.

**Comment by bjornharrtell** [comment]
Hey @dee-y, sorry did not see this issue until today. If you are still interested, I am looking for a logo and would welcome any suggestion.

**Comment by dee-y** [comment]
![flatgeobuf-01](https://user-images.githubusercontent.com/36637989/49340838-702d6680-f645-11e8-9890-9d306e3bfcf3.png)

Hello, here is a design i made. I incorporated the binary element with the zero in the middle and the whole as a one. Also made use of dead space to complete the element of location (geo). What do you think? also if you like this version, what color  would you like?

**Comment by bjornharrtell** [comment]
Made an SVG version at https://github.com/bjornharrtell/flatgeobuf/blob/master/logo.svg which I'm currently using. Thanks @dee-y!
