### ISSUE TITLE
Incomplete property types support

### ISSUE THREAD

**Issue by aaime** [bjornharrtell/flatgeobuf#32]
The list of known types is a bit limited:

https://github.com/bjornharrtell/flatgeobuf/blob/master/src/java/src/main/java/org/wololo/flatgeobuf/geotools/FeatureTypeConversions.java#L44

Should support all Number subtypes, Date, binary if possible, and probably fall back on string for anything else ("For real world code is complex, and full of terrors").

**Comment by bjornharrtell** [comment]
Thanks for reporting, definitely want to improve this. One reason for the situation is that the roundtrip tests I have for Java are based on GeoJSON which have a limited set of supported types. I'll see if I can come up with some more exhaustive tests and fix the situation, however it seems SimpleFeature does not provide any means of comparison.

**Comment by aaime** [comment]
Comparison... you mean the equals method for example? :-D

**Comment by bjornharrtell** [comment]
It looked like equals and hashCode wasn't overridden but mabye I didn't look hard enough. :)

**Comment by aaime** [comment]
SimpleFeatureImpl and SimpleFeatureTypeImpl both override equals and hashcode.
Btw, the error message does not report which type is causing the error, but I believe in the specific case it's BigDecimal (database configured with fixed number of decimal digits). That said, GeoTools will happily generate all subtypes of Number for you, I'm afraid, it just depends on the data source (the JDBC stores may be the richest source).

**Comment by bjornharrtell** [comment]
Tracking remaining known issues with #36 and #37.
