### ISSUE TITLE
TS/JS usage - fetch features for bounding box

### ISSUE THREAD

**Issue by underbluewaters** [bjornharrtell/flatgeobuf#38]
I'm having some trouble figuring out how to use the javascript module to retrieve a subset of features. Is there some way I can parse just the header of a very large flatgeobuf, use the index to identify byte ranges for a given bounding box, and then parse features for those bytes?

Eventually I'd like to stick a large flatgeobuf on s3 and run analysis on subsets of the data, using byte-range GET requests to just grab the data I need. Is that the sort of workflow this format is intended to support?

edit... looking at the format again, it appears I'd have trouble identifying how much of the file's header to retrieve in order to get the entire index. I'd appreciate any thoughts you might have on that as well.

**Comment by bjornharrtell** [comment]
Short answer is yes, this is the sort of workflow this format (when indexed) intends to support and it does in the C++ implementation (both GDAL and reference C++ at this repository) with good preliminary results (see http://osgeo-org.1560.x6.nabble.com/gdal-dev-Open-option-for-vectors-in-the-cloud-td5419994.html).

An indexed FlatGeobuf file consists of header, index (R-tree + feature offsets) and feature data. The R-tree is guaranteed to be balanced. The header is small. The R-tree nodes can be traversed and read on demand (C++ implementation at https://github.com/bjornharrtell/flatgeobuf/blob/10c8492b96df3a186b3e3ff05e6fb483288fb5f9/src/cpp/packedrtree.cpp#L266). The result of the R-tree index search is a set of array indexes for the feature offsets. Because the R-tree is balanced it's probable that the set of array indexes have high locality which can minimize byte-range GET requests for the actual feature offsets. The same goes for the feature data.

As you have noted the TS/JS reference implementation does not have this feature at this time, but I'd like to get that done and it is definitely a use case I want to prioritize and demonstrate as soon as possible.

**Comment by underbluewaters** [comment]
Thanks for the details! Right now I've got a bespoke format where I'm bundling subdivided vectors into multiple [geobuf](https://github.com/mapbox/geobuf) files on s3 and using a [flatbush](https://github.com/mourner/flatbush) index to reference them. This approach has the benefit of being more cacheable on the client, but requires custom tooling and results in hundreds of thousands of files which are more difficult to maintain on s3. I could imagine building a client that could sort of "tile" queries into discrete bounds to get those desirable cache qualities back.

Working out the index parsing in javascript is beyond what I can tackle right now but I'll try to dig into it if I have some time in the future.

**Comment by bjornharrtell** [comment]
Managed to get an initial implementation done. Test case demonstrating it via a local web server is at https://github.com/bjornharrtell/flatgeobuf/blob/8ce728447e8d2784e61eb84b137d6c3610593b8c/src/ts/geojson.spec.ts#L236-L242

It should already not pull more data than needed, but could be optimized to prefetch and cache data when possible to reduce the amount of requests. That should be doable by a more advanced implementation of the read method at https://github.com/bjornharrtell/flatgeobuf/blob/8ce728447e8d2784e61eb84b137d6c3610593b8c/src/ts/generic/featurecollection.ts#L83-L92

**Comment by underbluewaters** [comment]
Thanks for extra info Bjorn. I'm slowly trying to understand how this works and have a quick question. It looks like the readFeature method is fetching some metadata about each feature, then proceeding to read the rest of the bytes related to it based on the feature length. I'm I understanding that correctly?

https://github.com/bjornharrtell/flatgeobuf/blob/8ce728447e8d2784e61eb84b137d6c3610593b8c/src/ts/generic/featurecollection.ts#L160

That could prove to be a hurdle when fetching data over the network. I'm finding my s3 requests often have a significant amount of latency, even when using cloudfront, so making many sequential requests like that would be slow. In my case I could batch reading of the "feature header"s and feature data into two request salvos to minimize it. But maybe I'm missing something? Is the complete byte offset and size somewhere in the index?

**Comment by bjornharrtell** [comment]
Only the offset is in the index and the features are size prefixed. There is good reason to keep the index as small as possible. And you are right, with the naive implementation of read this will cause more roundtrips than one would like. However, the offsets you get from the index search are ordered and with good locality so a generic way to optimize the I/O is to implement prefetching for the read logic. This is what is done in the GDAL implementation (see https://gdal.org/user/virtual_file_systems.html#vsicurl-http-https-ftp-files-random-access) and it seems quite effective. One could perhaps optimize the read even more specifically for flatgeobuf as the index search also contains the index position and if positions are directly adjacent you could determine a more optimal buffer size to read but I think that is overkill.

**Comment by underbluewaters** [comment]
That clears it up for me a lot. Seems like there should be plenty of room to optimize requests based on adjacent indexes and prefixing. I've been playing with range requests to see how the browser cache behaves and it makes me optimistic that this could work well for my use case.

I'll be sure to post a demo if I get this idea working. I'm hoping to create an efficient process to clip polygons to the osm land dataset interactively in a digitizing tool.

**Comment by bjornharrtell** [comment]
Great to hear it. Glad to hear it might become useful for you.

If I had time I'd implement a generic prefetch in the reference TS/JS implementation and of course PRs are welcome.
