### ISSUE TITLE
Index optimizations for streaming

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/flatgeobuf#39]
Current index structure which is based on Flatbush might not be optimal for streaming traversal. Some observations:

* Traversal is backwards as tree has root in the end
* Feature offset array is separate from tree (is however nice to find a feature by id)

Perhaps both observations is simply a matter of I/O optimization and strategy.

**Comment by bjornharrtell** [comment]
In unscientific observations a search will require extensive seeking/reading even if the total amount of data used from the index is small, so some kind of I/O prefetch/cache is essential to improve performance.

GDAL prefetch/cache seems to be reduce the needed seeks/reads significantly, but still does not seem optimal. I assume this is because it's a generic prefetch/cache logic that works best if the streaming is done in a forward seek/read fashion. @rouault can you confirm?

**Comment by rouault** [comment]
Which cache mechanism are you refering to : /vsicurl/ or VSI_CACHE=YES ?

**Comment by bjornharrtell** [comment]
I was thinking about vsicurl.

**Comment by rouault** [comment]
Regarding vsicurl, its caching is a LRU mechanism. It has a prefetching heuristics when detecting that reads seem to be done in a sequential order. See https://github.com/OSGeo/gdal/blob/416fdf93e414d038a13e6dc744ca514f2671e2c7/gdal/port/cpl_vsil_curl.cpp#L1613

**Comment by bjornharrtell** [comment]
I've come to the conclusion that a better index structure should be possible.
