### ISSUE TITLE
Encoding in QGIS is set to "system"

### ISSUE THREAD

**Issue by tobwen** [bjornharrtell/flatgeobuf#42]
I know, this might be better issued in QGIS, but maybe that's a shorter way here.

When loading a FlatGeobuf file in QGIS , the encoding gets set to "system" by default, which is never UTF-8. So there are encoding problems. 

Could you please advertise the layer as UTF-8 only (or whatever the layer is in)? See https://github.com/OSGeo/gdal/issues/2254

**Comment by bjornharrtell** [comment]
Never UTF-8? On the contrary, all sane systems use UTF-8 by default. 🙂

Seriously though, seems like something I want to fix but is either a GDAL or QGIS issue, not sure yet. I'll begin by investigating the GDAL side of this.
