### ISSUE TITLE
Header: add metadata ?

### ISSUE THREAD

**Issue by rouault** [bjornharrtell/flatgeobuf#45]
It wouldn't probably hurt to offer the capability of having key=value metadata style in the header. Or maybe just a 'metadata' field that would hold a string that would be a JSon value.

**Comment by bjornharrtell** [comment]
Agreed, it have been on my mind. 🙂

**Comment by bjornharrtell** [comment]
So revisiting this and still interested in adding something along these lines, but unsure about how strict I want/should be. Is simply saying JSON useful or should it just be a string and up to the consumer/producer to decide the content/format? Or is there some schema suitable for structured metadata I could refer to as default with an optional override?

**Comment by rouault** [comment]
Different people will have different opinions on if metadata structure should be constrainted or not...
Looking for ISO 19115 and JSON, I came on: https://gist.github.com/JJediny/c6b419f218fd79bd478e5451377ebb73
My own feeling would be to just saying JSON.
