### ISSUE TITLE
JS: Import as module

### ISSUE THREAD

**Issue by kylebarron** [bjornharrtell/flatgeobuf#52]
I see that your Leaflet/OpenLayers examples load the built source in the `script` tag, from the `/dist/` folder
```
https://cdn.jsdelivr.net/npm/flatgeobuf@3.1.0/dist/flatgeobuf-geojson.min.js
https://cdn.jsdelivr.net/npm/flatgeobuf@3.1.0/dist/flatgeobuf-ol.min.js
```

However, there's currently no exported object from the module. So if I try to `require` the package, I get an error:
```js
require('flatgeobuf')
// Error: Cannot find module 'flatgeobuf'
```
This means that it's not possible now (I think) to use it with a bundler, like Webpack or Browserify.

It would be helpful to export some objects, to be able to do one of
```js
const flatgeobuf = require('flatgeobuf');
import flatgeobuf from "flatgeobuf";

flatgeobuf.deserialize(buffer)
```

**Comment by bjornharrtell** [comment]
That's strange, the dist bundles should be UMD modules as created by Rollup with config at https://github.com/bjornharrtell/flatgeobuf/blob/master/config/rollup.config.js and as such should export flatgeobuf as a module. That said, I've only used them without require.

Regardless it might be preferable to use the unbundled source if you want to use a bundler, it's in the lib folder of the npm package (fx. https://unpkg.com/browse/flatgeobuf@3.1.0/lib/ol.js).

Let me know how it goes and if problems remain please provide a more full example. I'll be glad to improve things but not sure yet what should be done.

**Comment by kylebarron** [comment]
I looked into it a little more; the issue is that your `package.json` is missing the [`main` field](https://docs.npmjs.com/files/package.json#main), so `require`/`import` doesn't know what to load.

Adding
```json
  "main": "./dist/flatgeobuf-geojson.min.js",
```
to the `package.json` successfully loads that script on `require`.


But still, you have the issue of what file to set as the `main` script. Since you have the `flatgeobuf-geojson` and `flatgeobuf-ol` separated out; currently you'd have to choose one or the other to set as the `main` script. I think personally I'd suggest having a higher-level `index.ts` file to define the package exports, so that a user could access `flatgeobuf.geojson`/`flatgeobuf.ol`. I think that because of tree shaking, there's no bundle size penalty when a user uses part of the package.

**Comment by bjornharrtell** [comment]
I see. I've always found the spec and use of https://docs.npmjs.com/files/package.json#main very unclear and error prone with different bundlers etc. What happens if you try require('flatgeobuf/lib/ol.js')?

**Comment by kylebarron** [comment]
When run from node (using `esm` to allow the embedded `import`), it fails:
```
> node -r esm
> require('flatgeobuf/lib/ol')
Thrown:
/Users/kyle/tmp/flatgeobuf2/node_modules/flatgeobuf/lib/ol/feature.js:1
Error: Cannot find module 'ol/Feature'
Require stack:
- /Users/kyle/tmp/flatgeobuf2/node_modules/flatgeobuf/lib/ol/feature.js
- /Users/kyle/tmp/flatgeobuf2/node_modules/flatgeobuf/lib/ol/featurecollection.js
- /Users/kyle/tmp/flatgeobuf2/node_modules/flatgeobuf/lib/ol.js
- <repl>
    at Object.<anonymous> (/Users/kyle/tmp/flatgeobuf2/node_modules/flatgeobuf/lib/ol/feature.js:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kyle/tmp/flatgeobuf2/node_modules/flatgeobuf/lib/ol/feature.js',
    '/Users/kyle/tmp/flatgeobuf2/node_modules/flatgeobuf/lib/ol/featurecollection.js',
    '/Users/kyle/tmp/flatgeobuf2/node_modules/flatgeobuf/lib/ol.js',
    '<repl>'
  ]
}
```

Though 
```
require('flatgeobuf/dist/flatgeobuf-geojson.min')
```
does work. I didn't realize you could set the paths like that.

But I don't think it's possible to use the built source to access the flat array internals, e.g. `geometry.xyArray()`, since it only exports the GeoJSON methods?

**Comment by bjornharrtell** [comment]
The first issue is because it cannot find OpenLayers modules. And of course that module is really only intended for use with OpenLayers.

The dist builds will hide internals yes.

You could try importing `require('flatgeobuf/lib/generic/featurecollection.js')` and use functions `deserialize` and/or `deserializeStream` which both expect you to supply a function `fromFeature` which acts as a callback for each feature where the feature object is the raw flatbuffers interface so you can access the flat array directly.

**Comment by kylebarron** [comment]
> The first issue is because it cannot find OpenLayers modules.

Duh, sorry, it's been a long day.

> You could try importing `require('flatgeobuf/lib/generic/featurecollection.js')` and use functions `deserialize` and/or `deserializeStream` which both expect you to supply a function `fromFeature` which acts as a callback for each feature where the feature object is the raw flatbuffers interface so you can access the flat array directly

Thanks, that's really helpful.

**Comment by kylebarron** [comment]
For the record, from my point of view it's standard for packages to have a `main` export, so that `require('flatgeobuf')` or `import ... from 'flatgeobuf'` doesn't fail.

Otherwise I'd suggest some documentation, so that the next person doesn't try `require('flatgeobuf')`, get confused, and make a new issue

**Comment by bjornharrtell** [comment]
Agreed, reopened as I would like to fix this at some point. :)

**Comment by bjornharrtell** [comment]
I also want to provide some guidance on whether to choose geojson, ol or generic modules.

**Comment by bjornharrtell** [comment]
As of 3.1.4 I have a single entry point module as main at https://github.com/bjornharrtell/flatgeobuf/blob/88f662c60321916edba8d1665a402b8b6251204f/package.json#L15 but I've not done any extensive testing. I tried to make some sensible docs using typedoc but I'm not satisfied yet. (https://unpkg.com/flatgeobuf@3.1.4/dist/doc/index.html contains alof of internals, but https://unpkg.com/flatgeobuf@3.1.4/dist/doc/modules/_flatgeobuf_.html shows the main entry point)

**Comment by bacloud22** [comment]
I confirm it is not working for me as well.

```js
import { geojson } from 'flatgeobuf';
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const buffer = fs.readFileSync(path.join(__dirname, '../data/geo/states.json'))
const fileContent = JSON.parse(buffer.toString());

const flatgeobuf = geojson.serialize(fileContent)
console.log(`Serialized input GeoJson into FlatGeobuf (${flatgeobuf.length} bytes)`)
```

So I'm having:

> internal/process/esm_loader.js:74
>     internalBinding('errors').triggerUncaughtException(
>                               ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ol' imported from /home/ubu/Documents/classified-ads/node_modules/flatgeobuf/lib/mjs/ol/feature.js

**Comment by bjornharrtell** [comment]
@bacloud22 yes ol is a peer dependency (https://github.com/flatgeobuf/flatgeobuf/blob/master/package.json#L63) but only for the ol sub modules. I suppose the node module loader isn't smart enough to figure out that it is not needed if you only use the geojson module. For now I would suggest you import serialize and or deserialize from the geojson module directly from `flatgeobuf/lib/mjs/geojson.js` instead.

**Comment by bacloud22** [comment]
It works great ! thanks
