### ISSUE TITLE
Project FlatBuffers.Core.csproj seems missing 

### ISSUE THREAD

**Issue by damianof** [bjornharrtell/flatgeobuf#53]
Project FlatBuffers.Core.csproj seems missing from flatgeobuf/src/net/ directory but referenced in solution file FlatGeobuf.sln

(unless I missed something)

**Comment by bjornharrtell** [comment]
That is part of upstream source which I've opted to not duplicate in this repo. Currently I use the bash script at https://github.com/bjornharrtell/flatgeobuf/blob/85ef2682f635bafa8533ecc12afa63200135e7ea/src/net/fetch.sh#L2 to fetch it locally and at CI. If upstream had a proper NuGet package it could probably be used instead but I don't feel it's important enough to try and push for that.

**Comment by damianof** [comment]
Thank you.
