### ISSUE TITLE
Webpack issues with entrypoint module

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/flatgeobuf#56]
In one dependent project I now (after changes for https://github.com/bjornharrtell/flatgeobuf/issues/52) get this problem:

ERROR in ./node_modules/flatgeobuf/lib/geojson.js
Module not found: Error: Can't resolve 'web-streams-polyfill/ponyfill' in '/home/bjorn/code/dai-edit-frontend/node_modules/flatgeobuf/lib'
 @ ./node_modules/flatgeobuf/lib/geojson.js 1:0-63 8:89-103
 @ /tmp/broccoli-57758Xe4x9f86Svt9/cache-465-bundler/staging/app.js
 @ multi /tmp/broccoli-57758Xe4x9f86Svt9/cache-465-bundler/staging/l.js /tmp/broccoli-57758Xe4x9f86Svt9/cache-465-bundler/staging/app.js⠋ buildingcleaning up...

This seems more of a webpack issue than anything else.. and I don't know how to fix it other than backtracking on the entry point module as I don't really see the use for it myself.

@kylebarron what is your take on this issue?

**Comment by kylebarron** [comment]
It looks like `web-streams-polyfill` is set as a `devDependency`, not as a `dependency`:
https://github.com/bjornharrtell/flatgeobuf/blob/c26b16506dac620c69a01ee0b4641e57f1b9c884/package.json#L52

So if you call it in your code, you need to move it to `dependencies` or to `peerDependencies`, which doesn't install it by default but is a signal that the user needs to have installed a copy to use the module.

**Comment by kylebarron** [comment]
E.g. here:
https://github.com/bjornharrtell/flatgeobuf/blob/942015ed8d6aeabba2bbbda8736da3e4f666be7e/src/ts/ol.ts#L1

You're importing from the module, so you can't set it as a `devDependency`

**Comment by bjornharrtell** [comment]
Thanks! Seems you are correct. Adjusted dependencies to what I believe is more correct, released as 3.1.5 and it works for me.
