### ISSUE TITLE
Support 4D coords

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/flatgeobuf#6]
As discussed in https://lists.osgeo.org/pipermail/proj/2019-June/008657.html it would be good if any future proof format of spatial features can explicitly represent temporal dimension i.e 4D.

By providing well known meta for possible dimensions X,Y,Z,M and T for a coordinate we can support 4D.

Open questions:
* Does unix timestamp work as temporal dimension?
* Can X,Y vs Z possibly/reasonably need separate temporal dimensions?

**Comment by bjornharrtell** [comment]
Feel free to chime in @kbevers

**Comment by kbevers** [comment]
> Does unix timestamp work as temporal dimension?

Theoretically yes, but the resolution is waaaaay to high. How much does a second of tectonic plate movement amount to? :) Decimalyears is the preferred time unit. It is what is used internally in PROJ and generally in all geodetic math formulas. Other units such as GPS-weeks also has merit. Ideally the unit is defined by WKT(2) metadata in the same manner as length units of the x, y and z components are today. I believe the [current standard](https://docs.opengeospatial.org/as/18-005r4/18-005r4.html) only deals with decimalyears but I would prepare for an extension that includes other time formats as well. [Here's](https://proj.org/operations/conversions/unitconvert.html#time-units) the ones PROJ support currently.

> Can X,Y vs Z possibly/reasonably need separate temporal dimensions?

So a time for each spatial dimensions amounting (up) to six coordinate components? Possibly, it could make sense to treat the horizontal and vertical parts separately (let's say you add heights to a 2D vector by adding them from a DTM) but I wouldn't do anything about that unless a standard at some point introduces that feature.

**Comment by bjornharrtell** [comment]
Nice, never used decimal year but it makes sense. :)

**Comment by kbevers** [comment]
We are talking about movements between 1 and 10 cm/year here. You don't exactly need 15 decimals of precision to store a time tag that is of geodetic relevance. Commonly 4 or 5 decimals are used, not more. 4 decimals roughly corresponds to a precision of an hour. Convince me that you need better resolution than that.

You could use (modified) julian date instead of decimal years if the top priority is to be compatible with common datetime formats, but that would then result in the transformation software having to do that conversion internally. But really, this should be governed by standards and currently it says decimalyears.

**Comment by bjornharrtell** [comment]
The tectonic apocalypse will happen in seconds! :D Just kidding, I'm not arguing we need higher precision and (like the other dimensions) I'm happy to bound it by double precision and let someone else fight about what the meaningful precision is.

**Comment by bjornharrtell** [comment]
I will see if I can grok the WKT(2) metadata enough to make an implementation proposal in my format.

**Comment by kbevers** [comment]
> The tectonic apocalypse will happen in seconds!

We have a word for that: Earthquakes ;-) And that is a whole different can of worms from a transformation stand point!

> I will see if I can grok the WKT(2) metadata enough to make an implementation proposal in my format.

Delegate the work to PROJ :-)

**Comment by bjornharrtell** [comment]
So just adding an explicit WKT(2) string as an optional part of SRS metadata and we are good to go for those who wants go deeper into spatial reference land? The previous idea was to simply keep an authority string and a number and perhaps it still makes sense to keep that in there too. Note that the flatgeobuf format itself simply holds double values *only* in a variable ordered number of dimensions. The max number of dimensions is 256 (constrained to a byte in header because it make no sense to me to even consider more than a handful dimensions).

What I like about decimal years is it is well represented by a double. At https://docs.opengeospatial.org/as/18-005r4/18-005r4.html#108 however ISO 8601 is mentioned and in general I feel I'm only confused by reading that document so I will stop. :)

**Comment by bjornharrtell** [comment]
This confuses me https://www.openstreetmap.org/user/StephaneP/diary/390290.

**Comment by kbevers** [comment]
Welcome to the fun world of geodesy :-)

**Comment by nyalldawson** [comment]
While @kbevers comments are true for geodesy, what about the use case where a t dimension is used to store time for e.g a linestring so that later movement /speed can be deduced? Then second or subsecond accuracy IS required.

**Comment by bjornharrtell** [comment]
@nyalldawson sounds like the use case you describe would carry time information as an object level attribute not as a native coordinate dimension?

**Comment by nyalldawson** [comment]
No - it would be node based. E.g imagine a GPS track of an object in motion where the timestamp is stored with each vertex.

Commonly m values are used as a workaround to do this in current formats. E.g @anitagraser describes this approach on her blog, see for example https://anitagraser.com/2017/10/28/movement-data-in-gis-10-open-tools-for-ais-tracks-from-marinecadastre-gov/

**Comment by bjornharrtell** [comment]
I have a hard time seeing a better solution than to use M for that use case (but then again, my imagination is limited). In my view, X, Y, Z (and now geodesy folks also want to hijack T) are "well known" dimensions associated with and described by spatial reference systems. M is a black sheep used for things that is not part of the spatial reference system within the bounds of what can be described by a single double dimension.

**Comment by anitagraser** [comment]
As @nyalldawson already laid out, for most use cases for a time dimension I can think of Decimalyears would be absolutely inappropriate.

**Comment by nyalldawson** [comment]
I personally find the "time as m" only a workaround around current format limitations. It would be great to see this fixed in modern formats. 

Because
1. I can easily foresee use cases where m AND t would be desirable to use together instead of being mutually exclusive.
2. For animation and time based filtering support, it would be great to have a standard way to record per node timestamps. Using m isn't this - you'd need to know exactly how the data creator has encoded/converted time within the values.

**Comment by bjornharrtell** [comment]
I would be open to add support for a named "TM" dimension as unsigned 64-bit values assumed to be nanosecond timestamps, if that makes sense. If done correctly it's entirely possible to add this and future dimensions (and other things) to flatgeobuf without breaking forward or backward compatibility due to how flatbuffers work. However, I'm not sure at which point these possible extensions to the simple features specification become non-simple. :)

**Comment by nyalldawson** [comment]
@bjornharrtell 

To be honest, I think you'll be ahead of the curve here, but I suspect that there'll soon be official standards for node-based-timestamps (or at least, feature based timestamps) in a simple feature extension.

**Comment by kbevers** [comment]
> I personally find the "time as m" only a workaround around current format limitations. It would be great to see this fixed in modern formats.

It definitely is! Recently it was mentioned on the PROJ list that OGC is working on updating standards so this is dealt with properly. I would expect that variations of XYZTM features will be included. I am not sure how open the OGC standardisation process is but if possible I would recommend that you guys try to follow along and get an idea of what's to come in the future.

**Comment by ChenyuWang98** [comment]
Allow me to ask a very idiotic question. What do the t, m, and tm dimensions represent?

**Comment by bjornharrtell** [comment]
The spatial index is two dimensional only.

The t, m and tm dimensions are documented at https://github.com/flatgeobuf/flatgeobuf/blob/31eda5f9fce91e2c2bc1082057cdf565ffa73eaf/src/fbs/feature.fbs#L9-L11.

**Comment by ChenyuWang98** [comment]
> The spatial index is two dimensional only.
> 
> The t, m and tm dimensions are documented at
> 
> https://github.com/flatgeobuf/flatgeobuf/blob/31eda5f9fce91e2c2bc1082057cdf565ffa73eaf/src/fbs/feature.fbs#L9-L11
> 
> .

 Whether support for 3D spatial indexing has not been considered, or has been considered and decided not to support 3D spatial indexing.

**Comment by bjornharrtell** [comment]
I have thought about 3D index once or twice but not seriously and have no plans to.
