### ISSUE TITLE
TS: 3D FlatGeobuf parsed to GeoJSON as 2D 

### ISSUE THREAD

**Issue by kylebarron** [bjornharrtell/flatgeobuf#66]
Here only the `XY` array portion of geometries are parsed to GeoJSON:

https://github.com/bjornharrtell/flatgeobuf/blob/7d9d5d59ee1da99d44da1dddebf2d57c38433e3c/src/ts/geojson/geometry.ts#L63-L76

I'd argue that GeoJSON should include the Z dimension if it exists. From the [spec](https://tools.ietf.org/html/rfc7946#section-4):

> An OPTIONAL third-position element SHALL be the height in meters above or below the WGS 84 reference ellipsoid.

**Comment by bjornharrtell** [comment]
Agreed, this is an oversight and bug.

**Comment by bjornharrtell** [comment]
Began work on this and realize why I didn't make it in the first place. It's non trivial to implement properly as the WKTParser implementation in JSTS also lacks support for more than 2 dimensions, and I need that for the test suite at least.

**Comment by bjornharrtell** [comment]
Required work in JSTS now tracked with https://github.com/bjornharrtell/jsts/issues/408.

**Comment by bjornharrtell** [comment]
As of https://github.com/bjornharrtell/flatgeobuf/commit/d34c237602066545413cc93ee30751193e739882 this should now be resolved.

**Comment by bjornharrtell** [comment]
This is now in 3.5.0 release at npm. @kylebarron if you get the chance to verify this I'd love to get feedback.
