### ISSUE TITLE
TS generic: TypeError: i is not a function

### ISSUE THREAD

**Issue by kylebarron** [bjornharrtell/flatgeobuf#67]
The non-GeoJSON `flatgeobuf` distribution fails for me (`flatgeobuf-geojson.min.js` works):

```js
var flatgeobuf_generic = require('flatgeobuf/dist/flatgeobuf.min.js')
var {readFileSync} = require('fs')
var path = '../test/data/ca_a.fgb'
var buf = readFileSync(path)
flatgeobuf_generic.deserialize(buf)
```

```
TypeError: i is not a function
    at /Users/kyle/unfolded/sandbox/flatgeobuf-parser/js-test/node_modules/flatgeobuf/dist/flatgeobuf.min.js:1:31696
    at Object.t.deserialize (/Users/kyle/unfolded/sandbox/flatgeobuf-parser/js-test/node_modules/flatgeobuf/dist/flatgeobuf.min.js:1:31720)
    at evalmachine.<anonymous>:1:20
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at run ([eval]:1054:15)
    at onRunRequest ([eval]:888:18)
    at onMessage ([eval]:848:13)
    at process.emit (events.js:310:20)
    at emit (internal/child_process.js:876:12)
```

Tested with this file, with geometry type `LINESTRING Z`:

[ca_a.fgb.zip](https://github.com/bjornharrtell/flatgeobuf/files/4886843/ca_a.fgb.zip)

**Comment by bjornharrtell** [comment]
That's not a valid call to the generic deserialize function. It requires not only input but also a second parameter fromFeature. See https://unpkg.com/flatgeobuf@3.3.4/dist/doc/modules/_generic_.html and https://unpkg.com/flatgeobuf@3.3.4/dist/doc/modules/_generic_featurecollection_.html#fromfeaturefn.

The idea is that the fromFeature funtion act as a callback that recieves the raw feature data as it is parsed and it's up to you implement it as the target is unknown in this case. The GeoJSON module uses the generic module and implements the fromFeature function at https://github.com/bjornharrtell/flatgeobuf/blob/7d9d5d59ee1da99d44da1dddebf2d57c38433e3c/src/ts/geojson/feature.ts#L16-L27 and uses it through the generic deserialize at https://github.com/bjornharrtell/flatgeobuf/blob/7d9d5d59ee1da99d44da1dddebf2d57c38433e3c/src/ts/geojson/featurecollection.ts#L43.

I can see this not being at all straight forward... but the generic module is a lower level abstraction than the GeoJSON module, so it requires more lower level knowledge.

Please reopen if you can demonstrate a valid use of the generic API that still fails.

**Comment by bjornharrtell** [comment]
I now see that the arrow function in the geojson source isn't needed, thanks. :) So the use there is now simply:

https://github.com/bjornharrtell/flatgeobuf/blob/78d98ec88db394d7f251085058f9b6fc63f65900/src/ts/geojson/featurecollection.ts#L43

**Comment by bjornharrtell** [comment]
Fun trivia - the removal of arrow function reduces flatgeobuf-geojson.min.js by 36 bytes and likely improves performance too. :D

**Comment by kylebarron** [comment]
I see. I find that auto-generated documentation very hard to read so I've been reading the code directly instead and missed that the generic `deserialize` expected another argument. (Also reading the code as I'm exploring a pure-Python decoding implementation).

Now that I understand how the generic deserialize works, I see that implementing extraction to typed arrays (https://github.com/bjornharrtell/flatgeobuf/issues/51) would be straightforward by writing a custom `fromFeature` argument.

**Comment by bjornharrtell** [comment]
Great. I'd like to expand on docs and examples but don't know when I can find time/priority for it. A pure Python reference impl. would be welcome.

**Comment by kylebarron** [comment]
Essentially only pure-Python decoding is currently of interest to me, for environments where I don't want to have a full GDAL dependency (I also made an issue on Fiona to connect the Python ecosystem to reading/writing through the FlatGeobuf GDAL driver: https://github.com/Toblerity/Fiona/issues/917). I'm not sure if you're interested in including a decoding-only Python implementation?

**Comment by bjornharrtell** [comment]
Decoding is half way to a full implementation, so yes. 🙂

In the end you might need encoding anyway to be able to write roundtrip tests, without those it might be very difficult to ensure that the decoding is bug free.
