### ISSUE TITLE
Extended column metadata

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/flatgeobuf#73]
As per current spec the metadata for a column consists of only name and type (https://github.com/bjornharrtell/flatgeobuf/blob/bb80f92a6d8d6ff277da7b7d590529e8f0c1fe83/src/fbs/header.fbs#L44-L46). It could be helpful to optionally be able to provide more details, fx. length/width/precision and nullability.

This could probably be added without breaking spec v3 backward compatibility.

**Comment by bjornharrtell** [comment]
@rouault do you have any advice here on useful colum/field metadata? I see that GDAL has width, precision, nullable, unique and also some notion of subtype that I'm not fully understanding.

**Comment by rouault** [comment]
> width, precision

They might be useful in some contexts, but some care must be taken on their definition. You might find tickets where the GDAL convention (based on shapefile convention, which matches the mapinfo one also I think) isn't exactly the one of PostgreSQL (or SQL in general).

> some notion of subtype that I'm not fully understanding.

subtype is mostly a hack to avoid introducing new main types, which require editing a lot of code in drivers and downstream code. For example a float32 number is described with type = OFTReal and subtype = OFSTFloat32. Most formats / users do not really care if it is a single or double precision, so they can just ignore the subtype.

**Comment by palmerj** [comment]
This schema metadata feature would be handy in the context of archival/snapshot storage of copies of geospatial datasets (e.g. versioned layers in a data lake). Having the metadata embedded in the storage file format is useful for downstream use and understanding of the original constraints placed on the data model. For example, replicating the data back into the database for analysis, it's useful for re-creating the DDL and applying primary key; or having the metadata available for displaying the data in a rendered table view. In these cases, it's essential to retain the source's original general schema including:

* The FID of the dataset (e.g. useful to understand the Primary key for change-set analysis of feature identification)
* data type
* data length or scale/width. e.g. VARCHAR(100), or NUMERIC(5, 2). 
* If the column is nullable.

**Comment by bjornharrtell** [comment]
Use case make sense but I don't think I want to aim to provide metadata for 100% re-creation of original schema (as it could be vendor specific) so I'll try to find out what is SQL generic or use PostgreSQL as reference.

**Comment by palmerj** [comment]
> Use case make sense but I don't think I want to aim to provide metadata for 100% re-creation of original schema (as it could be vendor specific) so I'll try to find out what is SQL generic or use PostgreSQL as reference.

Sounds good. Doesn't need to be complete. Maybe use the OGR abstraction model as a reference?

**Comment by bjornharrtell** [comment]
@rouault about GDAL precision and SQL precision and scale it seems to me the definition is that GDAL precision is equal to SQL scale and that SQL precision cannot be represented by GDAL at all. This is suprising to me and I will look into it some more, but mabye you can clarify if that is correct or if I'm misunderstanding?

**Comment by bjornharrtell** [comment]
After some tests it seems like GDAL width is used as SQL precision and GDAL precision is used as SQL scale. Not sure if I should do the same and remove the separate scale metadata field...

**Comment by bjornharrtell** [comment]
I've left out metadata about default value, more or less intentionally but I'm getting second thoughts. I'm not sure what value it has and it's spec is difficult, either need a generic string value (which behaviour will be hard to properly specify) or type specific default values.

**Comment by rouault** [comment]
GDAL's width and precision are the one of printf(), and correspond to DBF/Shapefile decimal formatting. So if width=6 and precision=2, the string gets formatted as "%6.2f", that is the total number of characters including negative sign and decimal point is 6, and number of digits after decimal point is 2.

**Comment by bjornharrtell** [comment]
I've also decided to add a general metadata field for a column, similar to the one for the whole dataset in the header. It could be used to for example provide information about the content of a binary type column.
