### ISSUE TITLE
Geoserver + flatGeobuff + OpenLayers running example

### ISSUE THREAD

**Issue by LucaGalvagno** [bjornharrtell/flatgeobuf#78]
Hi Bjorn,
is there any working example of Openlayers querying geoserver flatgeobuff features ?
I tried to create a vector layer in openlayer using the following code :
const vectorSource = new VectorSource({
  //strategy: allStrategy,
  strategy: bboxStrategy,
  loader: async function(extent) {
    const baseUrl = 'http://localhost:8080/geoserver/topp/ows'
    const baseParams = 'service=WFS&version=1.0.0&request=GetFeature'
    const typeNameParam = 'typeName=' + 'cite%3Aznet_mv_network'
    const bboxParam = 'bbox=' + extent.join(',')
    const outputFormatParam = 'outputFormat=application/flatgeobuf'
    const url = `${baseUrl}?${baseParams}&${typeNameParam}&${bboxParam}&${outputFormatParam}`
    const response = await fetch(url)
    //const response = await fetch('http://localhost:8080/geoserver/topp/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=topp%3Astates&outputFormat=application%2Fflatgeobuf')
    let asyncIterator = flatgeobuf.deserializeStream(response.body, ol)
    this.clear()
    for await (let feature of asyncIterator)
      this.addFeature(feature)
  }
});

It looks like the "fbs" coming from geoserver are not correctly received or creted in geoserver.

Thanks
Regards

**Comment by bjornharrtell** [comment]
Hi @LucaGalvagno, I'm looking into this now to see if I can reproduce your problem.

**Comment by bjornharrtell** [comment]
@LucaGalvagno I can't reproduce your issue, I can successfully consume output from GeoServer 2.17.2 with the FlatGeobuf extension and with FlatGeobuf 3.5.2 OpenLayers reference implementation (https://unpkg.com/flatgeobuf/dist/flatgeobuf-ol.min.js).

Your code example indicates you are using FlatGeobuf reference implementation for OpenLayers older than 3.1.x, please try with the latest version and observe that the API has changed somewhat (there is no longer a deserializeStream, only a deserialize method and it does not require an ol object.

I cannot provide a running GeoServer and specific example but the example at https://bjornharrtell.github.io/flatgeobuf/examples/openlayers/ demonstrates the current API usage and a fetch call that would be similar as when used with GeoServer as the source.
